spring:
  profiles:
    active: dev
  application:
    name: geteway
  cloud:
    consul:
      host: ${service.registry.consul-host}
      port: ${service.registry.consul-port}
      discovery:
        health-check-interval: 5s
        serviceName: ${spring.application.name}
        health-check-url: http://${service.registry.expose-host}:${service.registry.expose-port}${management.server.servlet.context-path}/info
        enabled: true
        # 默认设置queryPassing=false，即返回所有的服务，包括down掉的。通过配置改为true则可返回所有健康检查通过的服务
        query-passing: true
        prefer-ip-address: true
    gateway:
      routes:
        - id: 后台管理
          uri: lb://shiro-admin
          predicates:
            - Path=/shiro-admin/**
        - id: 支付服务
          uri: lb://pay-service
          predicates:
            - Path=/pay-service/**
          filters:
            #设置StripPrefix=1表示从二级url路径转发  http://localhost:port/shiro-admin/test将会转发到http://{admin}/test
            - StripPrefix=1


